### ISSUE TITLE
Deprecate readme.io

### ISSUE THREAD

**Issue by rjocoleman** [convox/convox.github.io#18]
@mattmanning 

You probably want to turn off the legacy docs - they show up higher on Google for me:

https://www.google.co.nz/search?hl=en&q=%22Instead%20of%20signing%20up%20for%20a%20multi-tenant%20PaaS%20like%20Heroku%22

**Comment by mattmanning** [comment]
@rjocoleman Thanks for the reminder. We just shut down the readme.io docs.
