### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mattmanning** [convox/convox.github.io#2]
Migrated/modified from https://github.com/convox/docs/issues/1 opened by @rjocoleman

The following Readme.io features are missing:

- [x] Search (https://swiftype.com/site-search is easy - it can be seen here https://middlemanapp.com/basics/install/, Google Custom Site Search is another option)
- [ ] Versions: I have some half baked code for scoping everything by version but it's not ready yet - I'm uncertain if this is a critical feature.

**Comment by mattmanning** [comment]
When I migrated from middleman to jekyll I had to drop some of the niceties, like markdown within callout divs, but most of the previous loose ends are tied up.

I think we can live with writing HTML for callouts, but a pure markdown solution would be nice. Perhaps we can use blockquotes.

**Comment by mattmanning** [comment]
Search and Versions are nice-to-haves, but I think at this early stage we can live without them. Search will become important when the number of docs gets large. Versions will become important as the product solidifies and backwards compatibility becomes a concern.

**Comment by rjocoleman** [comment]
@mattmanning 

I'm happy to put together a PR for search via algolia as discussed. 

However it needs to have the content pushed to populate the index on each deploy. It's also a paid product, I dont think the free plan would apply: https://www.algolia.com/pricing#Hacker

I can use Travis CI and a [custom deploy script](http://docs.travis-ci.com/user/deployment/script/) to push to algolia then push to the `gh-pages` branch.
This involves making a new git repo on travis and pushing it up.
The auto publish on GH would need to be disabled.
This would only deploy master.
A github personal access token and aloglia API key would be specified as [encrypted variables](http://docs.travis-ci.com/user/encryption-keys/) in `.travis.yml`.


Another option is to compile and push straight to S3. 
This would have less moving parts in the deploy script and can optionally handle things like cloudfront invalidations and http redirects.
AWS credentials and algolia API key would be encrypted in `.travis.yml`

**Comment by ddollar** [comment]
Closing for now
