### ISSUE TITLE
Architecture Diagram

### ISSUE THREAD

**Issue by mattmanning** [convox/convox.github.io#3]
Migrated from https://github.com/convox/docs/issues/2 opened by @nzoschke 

Draw an architecture diagram that explains how the AWS CF stacks, lambda custom resource handlers, apps, etc. work together.

Perhaps something that looks like this:

http://static3.creately.com/blog/wp-content/uploads/2012/07/AWS-architecture-basic.png

**Comment by mattmanning** [comment]
Comment migrated from https://github.com/convox/docs/issues/2#issuecomment-130115654 by @rjocoleman:

:+1:
there are two discrete questions in my head - the “what’s convox's architecture” and the “how does convox fit with aws"

Are these the same diagram, or different?

**Comment by jjperezaguinaga** [comment]
I'm trying to sell convox to my company, so I'll end up making an architecture diagram to explain the architecture to our technology department. I usually work with isometric diagrams like the followings:

![docker-ops](http://assets.jjperezaguinaga.com/articles/v1/front-end-ops-and-docker/04-front-end-ops-and-docker-containers.png)

![docker-comp](http://assets.jjperezaguinaga.com/articles/v1/front-end-ops-and-docker/03-front-end-ops-and-docker-components.png)

If you think the design matches your webpage, maybe you could use the same (i'm also open to suggestions, I'm happy to contribute to the project off time my job). I'll probably need some of your help to understand all the concepts around convox, but we can probably discuss all this in the slack channel, just let me know.

**Comment by ddollar** [comment]
This looks great! I'd be happy to answer any questions you have and we'd definitely be open to putting these on our site.

**Comment by alexbilbie** [comment]
@jjperezaguinaga just out of interest how do you generate those diagrams? By hand or with a program?

**Comment by jjperezaguinaga** [comment]
I usually draw a concept on paper, then draw them with [Affinity Designer](https://affinity.serif.com/buy-designer/) (<-- App Store Link). I'm halfway with the Convox ones, but here's another one I made for a CI/CD system using Convox (ignore how I decided to 3D the convox logo)

![CI/CD](https://s3.amazonaws.com/media-p.slid.es/uploads/388325/images/1819890/CI_CD.png)

**Comment by jjperezaguinaga** [comment]
![convox_architecture](https://cloud.githubusercontent.com/assets/1128312/10564957/87b2c34e-75c5-11e5-9ce2-f499acc4c294.png)

*(I already shared this in the public channel, but thought to put it here to get some additionally input)*

Here’s a very WIP of Convox’s diagram. Before I continue I would like to get some feedback and just making sure I got the basics clear. Atm the diagram still doesn’t show the following: Availability Zones, Security Groups, Encryption Keys, Kinesis Streams, Route Tables and Subnets. The goal of this draft is just to see if I got the current components right: 3 EC2 instances (each with 1 ELB), 2 Dynamo DB (Builds + Releases), 3 Buckets (Logs + Settings), 1 EC2 Cluster (with an initial tasks), 3 IAM Roles (+ each app adds 1 role), 1 Lambda Function (+ each app adds 1 function), 1 gateway, 1 initial ELB (each app adds one, but atm I have no idea where to put it), plus the CLI. 

Follow-up questions from here:

Which components am I missing?
Are all EC2 instances connected under the same net, group, security group?
Where is Convox REST API “living”?
Autoscale is enabled for EC2 instances, right or wrong?

There’s a very high chance I got something wrong (either component or relationship), so if you can gently point it out I’ll be more than happy to fix it. For me I think the overall goal is to have a very clear picture of Convox architecture so stakeholders from different technical backgrounds can see what Convox does.

**Comment by mattmanning** [comment]
Thanks for the diagram, @jjperezaguinaga. We have featured it here: http://convox.com/docs/what-is-a-rack/

**Comment by jjperezaguinaga** [comment]
:+1: nice!
