### ISSUE TITLE
Document sending logs to Papertrail

### ISSUE THREAD

**Issue by ddollar** [convox/convox.github.io#35]

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Femrpp21&#x2F;147-stuff"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Stuff</a>

**Comment by mattmanning** [comment]
http://convox.com/docs/papertrail/
